# Generated by Django 5.0.7 on 2025-02-03 14:11

import api.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount_allocated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_left', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=10, null=True)),
                ('start_date', models.DateField(verbose_name=datetime.date(2025, 2, 3))),
                ('end_date', models.DateField(blank=True, null=True)),
                ('user_username', models.CharField(default='', editable=False, max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('colour', models.CharField(max_length=7)),
                ('user_username', models.CharField(default='', editable=False, max_length=150)),
                ('count', models.IntegerField(default=0)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BaseTransaction',
            fields=[
                ('transaction_id', models.CharField(default=api.models.generate_transaction_id, max_length=8, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('type', models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income')], default='Expense', max_length=50)),
                ('category_name', models.CharField(default='', editable=False, max_length=150)),
                ('user_username', models.CharField(default='', editable=False, max_length=150)),
                ('budget_name', models.CharField(default='', editable=False, max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_owner', to=settings.AUTH_USER_MODEL)),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.budget')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_category', to='api.category')),
            ],
        ),
    ]
